version: '2.1'

networks:
  default:
    external: true
    name: test-net

services:
  tests:
    container_name: tests
    build: ./testing
    volumes:
      - "$WORKSPACE/allure-results:/tmp/allure"
      - "$WORKSPACE/logs:/src/logs"
      - "$WORKSPACE/allure-report:/tmp/allure-report"
    environment:
      - USERNAME
      - PASSWORD
      - WORKSPACE
    depends_on:
      myapp:
        condition: service_healthy

  mock:
    container_name: mock
    build: ./mock
    ports:
      - "4001:4001"
    healthcheck:
      test: [ "CMD", "curl", "mock:4001" ]
      timeout: 1s
      retries: 30
    depends_on:
      percona:
        condition: service_healthy

  percona:
    container_name: percona
    image: "percona:5.7"

    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "4002:3306"
    volumes:
      - ./configs/sql_config:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppass", "ping", "-h", "percona"]
      timeout: 1s
      retries: 30

  myapp:
    image: "myapp"
    container_name: myapp
    volumes:
      - ./configs/app-config:/tmp/config
    command: ["/app/myapp", "--config=/tmp/config/app-config.txt"]
    ports:
      - "4003:4003"
    healthcheck:
      test: [ "CMD", "curl", "myapp:4003" ]
      timeout: 1s
      retries: 30
    depends_on:
      percona:
        condition: service_healthy
      mock:
        condition: service_healthy

  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    volumes:
      - ./configs/selenoid_config/config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/selenoid_config/video:/opt/selenoid/video
      - ./configs/selenoid_config/logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./configs/selenoid_config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir",
               "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs",
               "-container-network", "test-net" ]
    ports:
      - "4004:4444"

  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui"
    ports:
      - "4005:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
